---
- name: installation of httpd
  yum:
    name: httpd
    state: present

- name: enable the httpd service
  service:
    name: httpd
    enabled: yes

- name: start the httpd service
  service:
    name: httpd
    state: started